name: Windows Build

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: Configure build for x86
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          sdk: 8.1
          toolset: 14.0
      - name: Compile
        run: |
          cl /W4 /WX iwv_forward.c /link /out:iwv_forward.exe
      - name: Dummy Run
        run: |
          & .\iwv_forward.exe testdata\IWV.TMP -n 2 -i 1
      - name: Store build result
        uses: actions/upload-artifact@v4
        with:
          name: build result
          path: iwv_forward.exe
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build result
          path: ./
      - uses: ncipollo/release-action@v1
        name: publish release
        with:
          artifacts: "iwv_forward.exe"
